image: archlinux
sources:
  - git@git.sr.ht:~yulqen/datamaps
packages:
  - python
  - python-pip
secrets:
  - 590eb309-3589-4444-bcbe-81f7a29024a8
tasks:
  - setup: |
      mkdir -p /home/build/Documents/datamaps/output
      mkdir -p /home/build/Documents/datamaps/input
  - test: |
      python -m venv /home/build/.venv
      cd datamaps
      /home/build/.venv/bin/pip install -e .
      /home/build/.venv/bin/pip install pytest
      /home/build/.venv/bin/pytest -q
